### ISSUE TITLE
class SnowflakeGenerator MAX_TS bug

### ISSUE THREAD

**Issue by xp3nn** [vd2org/snowflake#1]
The generator method bug.
The maximum timestamp has been reached in selected epoch
OverflowError: The maximum timestamp has been reached in selected epoch, so Snowflake cannot generate more IDs!
When initialize the generator class, we get the current time, if time greater the MAX_TS, that means the epoch params is invalid, the program throws the error directly.
current = int(time() * 1000)
if current >= MAX_TS

**Comment by vd2org** [comment]
Great idea. Thank you. Will be done later.
