### ISSUE TITLE
Machine Sequence Number in the Generator?

### ISSUE THREAD

**Issue by mf-hyunsoo-kang** [vd2org/snowflake#12]
It is correct implementation? I think Machine Sequence Number should be stored in the Machine that is identified by Machine ID, not a Generator. Imagine multiple Generator in the same machine, within a few nanoseconds.

**Comment by vd2org** [comment]
You must not use more than one generator with the same machine_id(called instance in our case) for the same purpose. The same thing happens when you run generators with the same machine_id on different computers.
