### ISSUE TITLE
Questions on using time.time() to get timestamp

### ISSUE THREAD

**Issue by zbaibg** [vd2org/snowflake#13]
Hi,

I want to know why you use time.time() to get the number of second and then time it by 1000 to get the milliseconds? In this case the information of millisecond-level would be missing. From my understanding of the snowflake, it aims to provide granularity at millisecond-level.

Best.

**Comment by mf-hyunsoo-kang** [comment]
time.time() returns "float" so there is no information loss. Btw, don't use this wrong-implemented package.

**Comment by ddorian** [comment]
@mf-hyunsoo-kang which one to use?

**Comment by vd2org** [comment]
@mf-hyunsoo-kang I don't understand which wrong with it.

**Comment by vd2org** [comment]
@zbaibg time.time() returns float with milliseconds. In order to get a time in milliseconds it should be multiplied by 1000 and converted to int.

https://docs.python.org/3/library/time.html#time.time
