### ISSUE TITLE
optimize runtime

### ISSUE THREAD

**Issue by knotgrass** [vd2org/snowflake#2]
I think we can optimize runtime in `SnowflakeGenerator` by change 
L74:  `current = int(time() * 1000)` -> `current = int(time() * 1000.)`
L112: `current = int(time() * 1000) - self._epo` -> `current = int(time() * 1000.) - self._epo`
Because multiply 2 float is faster twice than multiply a `float` and `int`. (note that time.time() return float)

**Comment by vd2org** [comment]
Hi! Good catch. 
Did you test it ?
If so, please send results. =)

**Comment by knotgrass** [comment]
@vd2org I just implemented and ran the test a few hours ago. 
The source test [here](https://github.com/Andy-Dang12/ID_generator/blob/c76daed52a91c2433642dad24280043ce7010413/test_runtime.py)
and the result is: 
```
start benchmark
runtime old 1000000000 time = 819.3113925457001
runtime new 1000000000 time = 806.03808760643

runtime old 1000000000 time = 525.9001922607422
runtime new 1000000000 time = 512.4601247310638
```

**Comment by vd2org** [comment]
Thank you a lot!
