### ISSUE TITLE
two questions about using Snowflake

### ISSUE THREAD

**Issue by peilongchencc** [vd2org/snowflake#3]
Hello, I have two questions about using Snowflake. Can you help answer them?

1st: This is my first time encountering Snowflake ID. Can you explain what the `42` means in `gen = SnowflakeGenerator(42)`? What guidelines should I follow when setting this value? Also, what are the roles of `epoch` and `seq` in the `parse` method?

2nd: When I ran the following code, I noticed that the displayed times were inconsistent.

```python
from snowflake import SnowflakeGenerator
import datetime

current_time = datetime.datetime.now()
print("current time:", current_time)

gen = SnowflakeGenerator(42)
snow_id = next(gen)
print("generate snowflake id:", snow_id)

from snowflake import Snowflake

sf = Snowflake.parse(snow_id)

print(f"{sf.timestamp = }")
print(f"{sf.instance = }")
print(f"{sf.epoch = }")
print(f"{sf.seq = }")
print(f"{sf.seconds = }")
print(f"{sf.milliseconds = }")
print(f"{sf.datetime = }")
print(f"{int(sf) = }")
```
result:
```txt
current time: 2023-08-30 17:05:43.994868
generate snowflake id: 7102577116159582209
sf.timestamp = 1693386343994
sf.instance = 42
sf.epoch = 0
sf.seq = 1
sf.seconds = 1693386343.994
sf.milliseconds = 1693386343994
sf.datetime = datetime.datetime(2023, 8, 30, 9, 5, 43, 994000)
int(sf) = 7102577116159582209
```

**Comment by knotgrass** [comment]
* `42` is machine_ID, 
* `epoch` is start time of your system, and you can choose start_time
You can see an example [here](https://github.com/Andy-Dang12/ID_generator/blob/main/idby_snowflake.py)

**Comment by peilongchencc** [comment]
> 

Thanks for your reply. It took several days, but I finally got it completely figured out.🥹
