### ISSUE TITLE
How to handle None result properly?

### ISSUE THREAD

**Issue by Badgerr** [vd2org/snowflake#5]
Hello.
`SnowflakeGenerator.__next__(self) ` returns optional integer.
I am not sure how to handle the situation when `None` value returned because I do need a value.
Should I wait for the next millisecond to guarantee non empty result?

**Comment by Badgerr** [comment]
@vd2org Sorry, any updates on this?

**Comment by vd2org** [comment]
Yep. The standard solution is to use optimistic loop:

```python
while not res := next(sf_gen):
   sleep(0)
```

In fact, the chance of such a situation occurring in Python is very small, but it is possible, so needs to be handled.

**Comment by Badgerr** [comment]
@vd2org Thanks a lot.
