### ISSUE TITLE
getting duplicate id in multi-threded environment (django)

### ISSUE THREAD

**Issue by anupsingh3292** [vd2org/snowflake#6]
I want to use snowflake ID generation in my project. so I am trying to use this library. but I am getting unique constraint error for the field primary key. I am using Django. can you please guide me, on how to set it up correctly to avoid getting duplicate IDs. like do I need any additional configurations?

**Comment by vd2org** [comment]
Hi! Each instance must have own `instance_id`. The standard schema of Django deploy is to use `uwsgi` or so on. It's spawning more than one process to serve requests. Thus, you have more than one instance of `snowflake` with the same `instance_id`.

So... you can't use the library in this way.

Instead, you have to create a separate service for generate ids.

**Comment by anupsingh3292** [comment]
I'm sorry for not getting back to you sooner. if I use a locking mechanism then can it be solved? if not can you please suggest to me how should I do it I am new to it. and our project is using UUID which I don't like. it'll be very helpful if you can provide in document, how to use it in a multi-threaded environment. I saw it everywhere but I couldn`t find it.

Here is my suggested answer. 

```python
from snowflake import SnowflakeGenerator
import threading

class ThreadSafeIdGeneratorService:
    def __init__(self, instance_id):
        self.gen = SnowflakeGenerator(ip_address_int)
        self.lock = threading.Lock()

    def generate_unique_id(self):
        with self.lock:
            return next(self.gen)
            ```
