### ISSUE TITLE
getting duplicate id error in django project multi threaded environment. (#6 re-open)

### ISSUE THREAD

**Issue by anupsingh3292** [vd2org/snowflake#7]
**previous question** 
      I want to use snowflake ID generation in my project. so I am trying to use this library. but I am getting unique constraint error for the field primary key. I am using Django. can you please guide me, on how to set it up correctly to avoid getting duplicate IDs. like do I need any additional configurations?_

**new question**
I'm sorry for not getting back to you sooner. if I use a locking mechanism then can it be solved? if not can you please suggest to me how should I do it I am new to it. and our project is using UUID which I don't like. it'll be very helpful if you can provide in document, how to use it in a multi-threaded environment. I saw it everywhere but I couldn`t find it.

Here is my suggested answer.

```python
from snowflake import SnowflakeGenerator
import threading

class ThreadSafeIdGeneratorService:
    def __init__(self, instance_id):
        self.gen = SnowflakeGenerator(ip_address_int)
        self.lock = threading.Lock()

    def generate_unique_id(self):
        with self.lock:
            return next(self.gen)
    ```

**Comment by vd2org** [comment]
It will work as long as you use threads. If you are using multiprocessing you will face the same issue. AFAIK `gunicorn` using multiprocessing.

**Comment by vd2org** [comment]
I think a separate service is the best way. The original design of the snowflake algo is based on this idea.

**Comment by anupsingh3292** [comment]
> I think a separate service is the best way. The original design of the snowflake algo is based on this idea.

separate service means a different server for generating IDs right? but instead of using thread lock if we use multiprocessing lock then? i will test it.

**Comment by vd2org** [comment]
Exactly.
